### ISSUE TITLE
sudoers done wrong

### ISSUE THREAD

**Issue by yrougy** [pparent76/Own-Mailbox_first-time-setup-ihm#2]
Hi there,

the  Omb-ihm/sudoers is very dangerous as it is.

You should never ever write 
www-data ALL=(ALL) NOPASSWD: /bin/su
If you need to run a command from another UID please see sudo -u option. This leads to Apache, or any other www-data uid process to have root access without authentication. 

You should never ever write:
- www-data ALL=(ALL) NOPASSWD: /usr/sbin/chpasswd. Your password will be changed without warning. Never allow apache to change root password. 
- www-data ALL=(ALL) NOPASSWD: /bin/cat. Apache can dump your hard drive. Apache can erase any file in your filesystem, Apache can copy, display any file content, any directory, including shadow, or anything else. Don't do that.
- www-data ALL=(ALL) NOPASSWD: /usr/sbin/useradd. You basically allow any attacker to create his own account on the machine. You should never add a user without authentication.
- www-data ALL=(ALL) NOPASSWD: /bin/cp. You can replace any file, including executable or libraries from Apache without any authentication. Just think of the consequences if it's libc.

For the service command, you must write the action, but I would strongly advice against anything more that reload. And service must not be alone...

You've done it wrong, you should consider an alternative. newaliases can be run from crontab, a lot of things can be run from at if you need it once, but never, ever put so many things with NOPASSWD in a sudoers.

**Comment by pparent76** [comment]
The first time interface, is actually designed to let the user configure its Own-Mailbox and take full control of it, out of a Factory state. So any way you turn it around the initial sudoers file will and has to allow apache to take full control of the machine. This initial sudoers file is then replaced by the final sudoers file with no NOPASSWD authorization, whatsoever, as soon as the configuration phase is over, and apache has no more privilege.

That being said, details of the implementation can and should for sure be improved.

**Comment by yrougy** [comment]
Even for a initial configuration, apache must never have the full control of the machine. Instead, it should trigger configuration scripts, but never do it by itself. A malicious user can create a backdoor with this kind of configuration even before the legitimate user can setup the box. The users cannot trust the configuration phase, since _any file_ can be tampered before the user setup its own-mailbox.

**Comment by pparent76** [comment]
Done!
